---

- name: Get secret definition from pvc
  include_tasks: apply_secrets.yml
  with_items:
    - secret_key_secret
    - admin_password_secret
    - broadcast_websocket_secret
    - postgres_secret
