---
services: docker
language: python

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

env:
  - DOCKER_API_VERSION=1.38

install:
  - pip3 install docker molecule molecule-docker yamllint ansible-lint openshift jmespath
  - ansible-galaxy collection install community.kubernetes operator_sdk.util

script:
  - molecule test -s test-local
