---

- name: Get AWX custom resource object
  k8s_info:
    version: v1beta1
    kind: AWX
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ deployment_name }}'
  register: _awx_cro

- name: Set AWX object
  set_fact:
    _awx: "{{ this_awx['resources'][0]['spec'] }}"

- name: Set names of backed up secrets in the CR spec
  set_fact:
    _awx: "{{ _awx | combine ({ item.key : item.value }) }}"
  with_items:
    - {"key": "secret_key_secret", "value": "{{ this_awx['resources'][0]['status']['secretKeySecret'] }}"}
    - {"key": "admin_password_secret", "value": "{{ this_awx['resources'][0]['status']['adminPasswordSecret'] }}"}
    - {"key": "broadcast_websocket_secret", "value": "{{ this_awx['resources'][0]['status']['broadcastWebsocketSecret'] }}"}
    - {"key": "postgres_configuration_secret", "value": "{{ this_awx['resources'][0]['status']['postgresConfigurationSecret'] }}"}

- name: Set AWX object
  set_fact:
    awx_spec:
      spec: "{{ _awx }}"

- name: Write awx object to pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    command: >-
      bash -c 'echo "$0" > {{ backup_dir  }}/awx_object' {{ awx_spec | to_yaml | quote  }}
