---

- name: Get AWX custom resource object
  k8s_info:
    version: v1beta1
    kind: AWX
    namespace: '{{ meta.namespace }}'
    name: '{{ deployment_name }}'
  register: _awx_cro

- name: Set AWX object
  set_fact:
    _awx: "{{ _awx_cro['resources'][0] }}"

- name: Set user specified spec
  set_fact:
    awx_spec: "{{ _awx['spec'] }}"

- name: Write awx object to pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ meta.name }}-db-management"
    command: >-
      bash -c 'echo "$0" > {{ backup_dir  }}/awx_object' {{ awx_spec | quote  }}
