---

- name: Create Temporary secrets file
  tempfile:
    state: file
    suffix: .json
  register: tmp_secrets

- name: Dump (generated) secret names from statuses and data into file
  include_tasks: dump_generated_secret.yml
  with_items:
    - secretKeySecret
    - adminPasswordSecret
    - broadcastWebsocketSecret
    - postgresConfigurationSecret

- name: Dump secret names from awx spec and data into file
  include_tasks: dump_secret.yml
  loop:
    - route_tls_secret
    - ingress_tls_secret
    - ldap_cacert_secret
    - bundle_cacert_secret
    - image_pull_secret
    - ee_pull_credentials_secret

- name: Nest secrets under a single variable
  set_fact:
    secrets: {"secrets": '{{ secret_dict }}'}
  no_log: true

- name: Write postgres configuration to pvc
  k8s_exec:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    command: >-
      bash -c "echo '{{ secrets | to_yaml }}' > {{ backup_dir }}/secrets.yml"
  no_log: true
