---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awxs.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWX
    listKind: AWXList
    plural: awxs
    singular: awx
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      description: Schema validation for the AWX CRD
      type: object
      properties:
        spec:
          type: object
          properties:
            deployment_type:
              type: string
              pattern: "^(tower|awx)(-)?.*$"
            external_database:
              type: boolean
              description: |
                If true you must supply a secret containing the location and credentials for
                connecting to the external database by a user who has permission to create
                and apply a schema.

                The secret should have the name: <custom resource name>-postgres-configuration and
                should look like:

                apiVersion: v1
                kind: Secret
                metadata:
                  name: <crname>-postgres-configuration
                  namespace: <target namespace>
                stringData:
                  host: <external ip or url resolvable by the cluster>
                  port: <external port, this usually defaults to 5432>
                  database: <desired database name>
                  username: <username to connect as>
                  password: <password to connect with>
                type: Opaque
          required:
            - deployment_type
