apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awxs.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWX
    listKind: AWXList
    plural: awxs
    singular: awx
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Schema validation for the AWX CRD
        properties:
          spec:
            properties:
              ca_trust_bundle:
                description: Path where the trusted CA bundle is available
                type: string
              deployment_type:
                description: Name of the deployment type
                type: string
              development_mode:
                description: If the deployment should be done in development mode
                type: boolean
              ldap_cacert_secret:
                description: Secret where can be found the LDAP trusted Certificate
                  Authority Bundle
                type: string
              tower_projects_persistence:
                description: Whether or not the /var/lib/projects directory will be persistent
                default: false
                type: boolean
              tower_projects_use_existing_claim:
                description: Using existing PersistentVolumeClaim
                type: string
                enum:
                  - _Yes_
                  - _No_
              tower_projects_existing_claim:
                description: PersistentVolumeClaim to mount /var/lib/projects directory
                type: string
              tower_projects_storage_class:
                description: Storage class for the /var/lib/projects PersistentVolumeClaim
                type: string
              tower_projects_storage_size:
                description: Size for the /var/lib/projects PersistentVolumeClaim
                default: 8Gi
                type: string
              tower_projects_storage_access_mode:
                description: AccessMode for the /var/lib/projects PersistentVolumeClaim
                default: ReadWriteMany
                type: string
              tower_admin_email:
                description: The admin user email
                type: string
              tower_admin_password_secret:
                description: Secret where the admin password can be found
                type: string
              tower_admin_user:
                default: admin
                description: Username to use for the admin account
                type: string
              tower_broadcast_websocket_secret:
                description: Secret where the broadcast websocket secret can be found
                type: string
              tower_create_preload_data:
                default: true
                description: Whether or not to preload data upon Tower instance creation
                type: boolean
              tower_ee_images:
                description: Registry path to the Execution Environment container
                  to use
                items:
                  properties:
                    image:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              tower_extra_volumes:
                description: Specify extra volumes to add to the application pod
                type: string
              tower_garbage_collect_secrets:
                default: false
                description: Whether or not to remove secrets upon instance removal
                type: boolean
              tower_hostname:
                description: The hostname of the instance
                type: string
              tower_image:
                description: Registry path to the application container to use
                type: string
              tower_image_pull_policy:
                default: IfNotPresent
                description: The image pull policy
                enum:
                - Always
                - always
                - Never
                - never
                - IfNotPresent
                - ifnotpresent
                type: string
              tower_image_pull_secret:
                description: The image pull secret
                type: string
              tower_ingress_annotations:
                description: Annotations to add to the ingress
                type: string
              tower_ingress_tls_secret:
                description: Secret where the ingress TLS secret can be found
                type: string
              tower_ingress_type:
                description: The ingress type to use to reach the deployed instance
                enum:
                - none
                - Ingress
                - ingress
                - Route
                - route
                - LoadBalancer
                - loadbalancer
                type: string
              tower_loadbalancer_annotations:
                description: Annotations to add to the loadbalancer
                type: string
              tower_loadbalancer_port:
                default: 80
                description: Port to use for the loadbalancer
                type: integer
              tower_loadbalancer_protocol:
                default: http
                description: Protocol to use for the loadbalancer
                enum:
                - http
                - https
                type: string
              tower_node_selector:
                description: nodeSelector for the AWX pods
                type: string
              tower_old_postgres_configuration_secret:
                description: Secret where the old database configuration can be found
                  for data migration
                type: string
              tower_postgres_configuration_secret:
                description: Secret where the database configuration can be found
                type: string
              tower_postgres_data_path:
                description: Path where the PostgreSQL data are located
                type: string
              tower_postgres_image:
                description: Registry path to the PostgreSQL container to use
                type: string
              tower_postgres_resource_requirements:
                description: Resource requirements for the PostgreSQL container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              tower_postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
              tower_redis_image:
                description: Registry path to the redis container to use
                type: string
              tower_replicas:
                default: 1
                description: Number of instance replicas
                format: int32
                type: integer
              tower_route_host:
                description: The DNS to use to points to the instance
                type: string
              tower_route_tls_secret:
                description: Secret where the TLS related credentials are stored
                type: string
              tower_route_tls_termination_mechanism:
                default: Edge
                description: The secure TLS termination mechanism to use
                enum:
                - Edge
                - edge
                - Passthrough
                - passthrough
                type: string
              tower_secret_key_secret:
                description: Secret where the secret key can be found
                type: string
              tower_task_args:
                items:
                  type: string
                type: array
              tower_task_command:
                items:
                  type: string
                type: array
              tower_task_extra_env:
                type: string
              tower_task_extra_volume_mounts:
                type: string
              tower_task_privileged:
                default: false
                description: If a privileged security context should be enabled
                type: boolean
              tower_task_resource_requirements:
                description: Resource requirements for the task container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              tower_tolerations:
                description: node tolerations for the AWX pods
                type: string
              tower_web_args:
                items:
                  type: string
                type: array
              tower_web_command:
                items:
                  type: string
                type: array
              tower_web_extra_env:
                type: string
              tower_web_extra_volume_mounts:
                type: string
              tower_web_resource_requirements:
                description: Resource requirements for the web container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
            type: object
          status:
            properties:
              conditions:
                description: The resulting conditions when a Service Telemetry is
                  instantiated
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              towerAdminPasswordSecret:
                description: Admin password of the deployed instance
                type: string
              towerAdminUser:
                description: Admin user of the deployed instance
                type: string
              towerImage:
                description: URL of the image used for the deployed instance
                type: string
              towerMigratedFromSecret:
                description: The secret used for migrating an old Tower.
                type: string
              towerURL:
                description: URL to access the deployed instance
                type: string
              towerVersion:
                description: Version of the deployed instance
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
