apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: awxs.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWX
    listKind: AWXList
    plural: awxs
    singular: awx
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Schema validation for the AWX CRD
        properties:
          spec:
            properties:
              admin_email:
                description: The admin user email
                type: string
              admin_password_secret:
                description: Secret where the admin password can be found
                type: string
              admin_user:
                default: admin
                description: Username to use for the admin account
                type: string
              api_version:
                description: apiVersion of the deployment type
                type: string
              broadcast_websocket_secret:
                description: Secret where the broadcast websocket secret can be found
                type: string
              bundle_cacert_secret:
                description: Secret where can be found the trusted Certificate Authority Bundle
                type: string
              ca_trust_bundle:
                description: Path where the trusted CA bundle is available
                type: string
              control_plane_ee_image:
                description: Registry path to the Execution Environment container
                  image to use on control plane pods
                type: string
              create_preload_data:
                default: true
                description: Whether or not to preload data upon instance creation
                type: boolean
              deployment_type:
                description: Name of the deployment type
                type: string
              development_mode:
                description: If the deployment should be done in development mode
                type: boolean
              ee_extra_env:
                type: string
              ee_extra_volume_mounts:
                description: Specify volume mounts to be added to Execution container
                type: string
              ee_images:
                description: Registry path to the Execution Environment container
                  to use
                items:
                  properties:
                    image:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              ee_pull_credentials_secret:
                description: Secret where pull credentials for registered ees can
                  be found
                type: string
              ee_resource_requirements:
                description: Resource requirements for the ee container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              extra_settings:
                description: Extra settings to specify for the API
                items:
                  properties:
                    setting:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
              extra_volumes:
                description: Specify extra volumes to add to the application pod
                type: string
              garbage_collect_secrets:
                default: false
                description: Whether or not to remove secrets upon instance removal
                type: boolean
              hostname:
                description: The hostname of the instance
                type: string
              image:
                description: Registry path to the application container to use
                type: string
              image_pull_policy:
                default: IfNotPresent
                description: The image pull policy
                enum:
                - Always
                - always
                - Never
                - never
                - IfNotPresent
                - ifnotpresent
                type: string
              image_pull_secret:
                description: The image pull secret
                type: string
              image_version:
                description: Application container image version to use
                type: string
              ingress_annotations:
                description: Annotations to add to the Ingress Controller
                type: string
              ingress_tls_secret:
                description: Secret where the Ingress TLS secret can be found
                type: string
              ingress_type:
                description: The ingress type to use to reach the deployed instance
                enum:
                - none
                - Ingress
                - ingress
                - Route
                - route
                type: string
              init_container_image:
                description: Registry path to the init container to use
                type: string
              init_container_image_version:
                description: Initcontainer image version to use
                type: string
              kind:
                description: Kind of the deployment type
                type: string
              ldap_cacert_secret:
                description: Secret where can be found the LDAP trusted Certificate
                  Authority Bundle
                type: string
              loadbalancer_annotations:
                description: Annotations to add to the loadbalancer
                type: string
              loadbalancer_port:
                default: 80
                description: Port to use for the loadbalancer
                type: integer
              loadbalancer_protocol:
                default: http
                description: Protocol to use for the loadbalancer
                enum:
                - http
                - https
                type: string
              node_selector:
                description: nodeSelector for the pods
                type: string
              old_postgres_configuration_secret:
                description: Secret where the old database configuration can be found
                  for data migration
                type: string
              postgres_configuration_secret:
                description: Secret where the database configuration can be found
                type: string
              postgres_data_path:
                description: Path where the PostgreSQL data are located
                type: string
              postgres_image:
                description: Registry path to the PostgreSQL container to use
                type: string
              postgres_image_version:
                description: PostgreSQL container image version to use
                type: string
              postgres_label_selector:
                description: Label selector used to identify postgres pod for data
                  migration
                type: string
              postgres_resource_requirements:
                description: Resource requirements for the PostgreSQL container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                    type: object
                type: object
              postgres_selector:
                description: nodeSelector for the Postgres pods
                type: string
              postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
              postgres_storage_requirements:
                description: Storage requirements for the PostgreSQL container
                properties:
                  limits:
                    properties:
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      storage:
                        type: string
                    type: object
                type: object
              postgres_tolerations:
                description: node tolerations for the Postgres pods
                type: string
              projects_existing_claim:
                description: PersistentVolumeClaim to mount /var/lib/projects directory
                type: string
              projects_persistence:
                default: false
                description: Whether or not the /var/lib/projects directory will be
                  persistent
                type: boolean
              projects_storage_access_mode:
                default: ReadWriteMany
                description: AccessMode for the /var/lib/projects PersistentVolumeClaim
                type: string
              projects_storage_class:
                description: Storage class for the /var/lib/projects PersistentVolumeClaim
                type: string
              projects_storage_size:
                default: 8Gi
                description: Size for the /var/lib/projects PersistentVolumeClaim
                type: string
              projects_use_existing_claim:
                description: Using existing PersistentVolumeClaim
                enum:
                - _Yes_
                - _No_
                type: string
              redis_image:
                description: Registry path to the redis container to use
                type: string
              redis_image_version:
                description: Redis container image version to use
                type: string
              replicas:
                default: 1
                description: Number of instance replicas
                format: int32
                type: integer
              route_host:
                description: The DNS to use to points to the instance
                type: string
              route_tls_secret:
                description: Secret where the TLS related credentials are stored
                type: string
              route_tls_termination_mechanism:
                default: Edge
                description: The secure TLS termination mechanism to use
                enum:
                - Edge
                - edge
                - Passthrough
                - passthrough
                type: string
              secret_key_secret:
                description: Secret where the secret key can be found
                type: string
              service_account_annotations:
                description: ServiceAccount annotations
                type: string
              service_labels:
                description: Additional labels to apply to the service
                type: string
              service_type:
                description: The service type to be used on the deployed instance
                enum:
                - LoadBalancer
                - loadbalancer
                - ClusterIP
                - clusterip
                - NodePort
                - nodeport
                type: string
              task_args:
                items:
                  type: string
                type: array
              task_command:
                items:
                  type: string
                type: array
              task_extra_env:
                type: string
              task_extra_volume_mounts:
                description: Specify volume mounts to be added to Task container
                type: string
              task_privileged:
                default: false
                description: If a privileged security context should be enabled
                type: boolean
              task_resource_requirements:
                description: Resource requirements for the task container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              tolerations:
                description: node tolerations for the pods
                type: string
              web_args:
                items:
                  type: string
                type: array
              web_command:
                items:
                  type: string
                type: array
              web_extra_env:
                type: string
              web_extra_volume_mounts:
                description: Specify volume mounts to be added to the Web container
                type: string
              web_resource_requirements:
                description: Resource requirements for the web container
                properties:
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
            type: object
          status:
            properties:
              URL:
                description: URL to access the deployed instance
                type: string
              adminPasswordSecret:
                description: Admin password secret name of the deployed instance
                type: string
              adminUser:
                description: Admin user of the deployed instance
                type: string
              broadcastWebsocketSecret:
                description: Broadcast websocket secret name of the deployed instance
                type: string
              conditions:
                description: The resulting conditions when a Service Telemetry is
                  instantiated
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              image:
                description: URL of the image used for the deployed instance
                type: string
              migratedFromSecret:
                description: The secret used for migrating an old instance.
                type: string
              postgresConfigurationSecret:
                description: Postgres Configuration secret name of the deployed instance
                type: string
              secretKeySecret:
                description: Secret key secret name of the deployed instance
                type: string
              version:
                description: Version of the deployed instance
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
