---
tower_hostname: example-tower.test
tower_secret_key: aabbcc

tower_admin_user: test
tower_admin_email: test@example.com
tower_admin_password: changeme

# Use these image versions for Ansible Tower.
tower_task_image: quay.io/ansible-tower/ansible-tower:3.6.1
tower_web_image: quay.io/ansible-tower/ansible-tower:3.6.1

# Use these image versions for Ansible AWX.
# tower_task_image: ansible/awx_task:9.0.1
# tower_web_image: ansible/awx_web:9.0.1

tower_create_preload_data: true

tower_task_replicas: "1"

tower_task_mem_request: 1Gi
tower_task_cpu_request: 500m

tower_web_mem_request: 2Gi
tower_web_cpu_request: 1000m

tower_memcached_image: memcached:alpine

tower_rabbitmq_image: rabbitmq:3

tower_postgres_pass: awxpass
tower_postgres_image: postgres:9.6
tower_postgres_storage_request: 8Gi
tower_postgres_storage_class: ''
