---
- name: Check for specified broadcast websocket secret configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ broadcast_websocket_secret }}'
  register: _custom_broadcast_websocket
  no_log: "{{ no_log }}"
  when: broadcast_websocket_secret | length

- name: Check for default broadcast websocket secret configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-broadcast-websocket'
  register: _default_broadcast_websocket
  no_log: "{{ no_log }}"

- name: Set broadcast websocket secret
  set_fact:
    # yamllint disable-line rule:line-length
    _broadcast_websocket_secret: '{{ _custom_broadcast_websocket["resources"] | default([]) | length | ternary(_custom_broadcast_websocket, _default_broadcast_websocket) }}'  # noqa 204
  no_log: "{{ no_log }}"

- block:
    - name: Create broadcast websocket secret
      k8s:
        apply: true
        definition: "{{ lookup('template', 'secrets/broadcast_websocket_secret.yaml.j2') }}"
      no_log: "{{ no_log }}"

    - name: Read broadcast websocket secret
      k8s_info:
        kind: Secret
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-broadcast-websocket'
      register: _generated_broadcast_websocket
      no_log: "{{ no_log }}"

  when: not _broadcast_websocket_secret['resources'] | default([]) | length

- name: Set broadcast websocket secret
  set_fact:
    # yamllint disable-line rule:line-length
    __broadcast_websocket_secret: '{{ _generated_broadcast_websocket["resources"] | default([]) | length | ternary(_generated_broadcast_websocket, _broadcast_websocket_secret)  }}'  # noqa 204
  no_log: "{{ no_log }}"

- name: Store broadcast websocket secret name
  set_fact:
    broadcast_websocket_secret_value: "{{ __broadcast_websocket_secret['resources'][0]['data']['secret'] | b64decode }}"
  no_log: "{{ no_log }}"
