---
# Required: specify name of tower deployment to restore to
deployment_name: ''
kind: 'AWXRestore'
api_version: '{{ deployment_type }}.ansible.com/v1beta1'

# Required: specify a pre-created PVC (name) to restore from
backup_pvc: ''
backup_pvc_namespace: '{{ ansible_operator_meta.namespace }}'

# Required: backup name, found on the awxbackup object
backup_dir: ''
