---
# Required: specify name of tower deployment to backup from
deployment_name: ''
kind: 'AWXBackup'
api_version: '{{ deployment_type }}.ansible.com/v1beta1'

# Specify a pre-created PVC (name) to backup to
backup_pvc: ''
backup_pvc_namespace: "{{ ansible_operator_meta.namespace }}"

# Size of backup PVC if created dynamically
backup_storage_requirements: ''

# Set no_log settings on certain tasks
no_log: 'true'

# Variable to set when you want backups to be cleaned up when the CRD object is deleted
clean_backup_on_delete: false

# Variable to signal that this role is being run as a finalizer
finalizer_run: false

# Allow additional parameters to be added to the pg_dump backup command
pg_dump_suffix: ''
